// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "Fresh",
    platforms: [.macOS(.v15)],
    targets: [
        // The Rust core as a static library with its C header; build.sh generates both.
        .binaryTarget(name: "FreshCoreFFI", path: "Generated/FreshCoreFFI.xcframework"),
        // Swift bindings for the core, generated by uniffi-bindgen.
        .target(name: "FreshCore", dependencies: ["FreshCoreFFI"], path: "Generated/FreshCore"),
        .executableTarget(name: "Fresh", dependencies: ["FreshCore"], path: "Sources/Fresh"),
    ]
)
